"""Constants and small data records from AtlasTypes.h."""

from dataclasses import dataclass, field

CMD_JMP1 = 0
CMD_JMP2 = 1
CMD_SMA = 2
CMD_HDR = 3
CMD_STRTYPE = 4
CMD_ADDTBL = 5
CMD_ACTIVETBL = 6
CMD_VAR = 7
CMD_WUB = 8
CMD_WBB = 9
CMD_WHB = 10
CMD_WLB = 11
CMD_W16 = 12
CMD_W24 = 13
CMD_W32 = 14
CMD_EMBSET = 15
CMD_EMBTYPE = 16
CMD_EMBWRITE = 17
CMD_BREAK = 18
CMD_PTRTBL = 19
CMD_WRITETBL = 20
CMD_PTRLIST = 21
CMD_WRITELIST = 22
CMD_AUTOWRITETBL = 23
CMD_AUTOWRITELIST = 24
CMD_CREATEPTR = 25
CMD_WRITEPTR = 26
CMD_LOADEXT = 27
CMD_EXECEXT = 28
CMD_DISABLETABLE = 29
CMD_DISABLELIST = 30
CMD_PASCALLEN = 31
CMD_AUTOEXEC = 32
CMD_DISABLEEXEC = 33
CMD_INSERT = 34
CMD_WARN = 35
CMD_FILL = 36
CMD_W08_BYTE = 37
CMD_SAVE_PC = 38
CMD_LOAD_PC = 39
CMD_SET_INDEX = 40
CMD_WRITE_INDEX = 41
CMD_ALIGN = 42
CMD_EMBCLEAR = 43
CMD_SAVE_INDEX = 44
CMD_LOAD_INDEX = 45
CMD_W08_BYTE_FILE = 46
CMD_WRITE_INDEX_FILE = 47
CMD_FILL_FILE = 48
CMD_EMBSET_REL = 49
CMD_EMBWRITE_REL = 50
CMD_SAVE_PTRTABLE = 51
CMD_LOAD_PTRTABLE = 52
CMD_FILL_RANGE = 53

CommandCount = CMD_FILL_RANGE + 1

CommandStrings = [
    "JMP", "JMP", "SMA", "HDR", "STRTYPE", "ADDTBL", "ACTIVETBL", "VAR",
    "WUB", "WBB", "WHB", "WLB", "W16", "W24", "W32", "EMBSET",
    "EMBTYPE", "EMBWRITE", "BREAK", "PTRTBL", "WRITE", "PTRLIST",
    "WRITE", "AUTOWRITE", "AUTOWRITE", "CREATEPTR", "WRITE", "LOADEXT",
    "EXECEXT", "DISABLE", "DISABLE", "PASCALLEN", "AUTOEXEC", "DISABLE",
    "INSERT", "WARN", "FILL", "W08BYTE", "SAVEPC", "LOADPC", "SETINDEX",
    "WRITEINDEX", "ALIGN", "EMBCLEAR", "SAVEINDEX", "LOADINDEX",
    "W08BYTE", "WRITEINDEX", "FILL", "EMBSETREL", "EMBWRITEREL",
    "SAVEPTRTABLE", "LOADPTRTABLE", "FILL",
]

P_INVALID = 0
P_VOID = 1
P_STRING = 2
P_VARIABLE = 3
P_NUMBER = 4
P_DOUBLE = 5
P_TABLE = 6
P_POINTERTABLE = 7
P_POINTERLIST = 8
P_CUSTOMPOINTER = 9
P_EXTENSION = 10

TypeCount = 11
TypeStrings = [
    "INVALID", "VOID", "STRING", "VARIABLE", "NUMBER", "DOUBLE", "TABLE",
    "POINTERTABLE", "POINTERLIST", "CUSTOMPOINTER", "EXTENSION",
]

Types = [
    [P_NUMBER], [P_NUMBER, P_NUMBER], [P_STRING], [P_NUMBER], [P_STRING],
    [P_STRING, P_TABLE], [P_TABLE], [P_VARIABLE, P_VARIABLE], [P_NUMBER],
    [P_NUMBER], [P_NUMBER], [P_NUMBER], [P_NUMBER], [P_NUMBER], [P_NUMBER],
    [P_NUMBER], [P_STRING, P_NUMBER, P_NUMBER], [P_NUMBER], [P_VOID],
    [P_POINTERTABLE, P_NUMBER, P_NUMBER, P_CUSTOMPOINTER], [P_POINTERTABLE],
    [P_POINTERLIST, P_STRING, P_CUSTOMPOINTER], [P_POINTERLIST],
    [P_POINTERTABLE, P_STRING], [P_POINTERLIST, P_STRING],
    [P_CUSTOMPOINTER, P_STRING, P_NUMBER, P_NUMBER],
    [P_CUSTOMPOINTER, P_NUMBER], [P_EXTENSION, P_STRING],
    [P_EXTENSION, P_STRING], [P_POINTERTABLE, P_STRING],
    [P_POINTERLIST, P_STRING], [P_NUMBER], [P_EXTENSION, P_STRING, P_STRING],
    [P_STRING, P_STRING], [P_STRING, P_STRING], [P_NUMBER, P_STRING],
    [P_NUMBER, P_NUMBER], [P_NUMBER, P_NUMBER], [P_STRING], [P_STRING],
    [P_NUMBER, P_NUMBER], [P_NUMBER, P_NUMBER], [P_NUMBER], [P_VOID],
    [P_STRING], [P_STRING], [P_NUMBER, P_NUMBER, P_STRING],
    [P_NUMBER, P_NUMBER, P_STRING], [P_NUMBER, P_NUMBER, P_NUMBER, P_STRING],
    [P_NUMBER], [P_NUMBER], [P_POINTERTABLE, P_STRING],
    [P_POINTERTABLE, P_STRING], [P_NUMBER, P_NUMBER, P_NUMBER],
]

ParamCount = [
    1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 4, 1,
    3, 1, 2, 2, 4, 2, 2, 2, 2, 2, 1, 3, 2, 2, 2, 2, 2, 1, 1, 2,
    2, 1, 1, 1, 1, 3, 3, 4, 1, 1, 2, 2, 3,
]


@dataclass
class Parameter:
    Value: str = ""
    Type: int = P_INVALID


@dataclass
class Command:
    Function: int = 0
    Parameters: list[Parameter] = field(default_factory=list)
    Line: int = 0


@dataclass
class AtlasBlock:
    Commands: list[Command] = field(default_factory=list)
    TextLines: list[str] = field(default_factory=list)
    StartLine: int = -1
